#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

APP="$1"; TMP_WORK_DIR="$2"; REV="$3"

[[ ! -f "$TMP_WORK_DIR/.dokku-monorepo" ]] && exit

dokku_log_info2 "Monorepo detected"

while IFS="=" read -u 10 -a line || [[ -n $line ]]; do
  [[ "${line[0]}" == "#"* || "${line[1]}" == "" ]] && continue
  [[ $APP != *"${line[0]}"* ]] && continue

  app_subdir="${line[1]}"
  dokku_log_info2 "Installing from ./$app_subdir"

  app_root="$TMP_WORK_DIR/$app_subdir"

  # Move the app we want to deploy to a temp directory.
  APP_TMP_DIR="$(mktemp -d)"
  mv "$app_root" "$APP_TMP_DIR"

  # The `rm -rf` and the `mv` commands for hidden files will
  # print out errors and/or return a non-zero code even though
  # they succeed. Suppress these so that the script can continue.

  # Delete all files that aren't related to the app we are trying
  # to deploy
  rm -rf "$TMP_WORK_DIR"/* > /dev/null 2>&1 || true
  rm -rf "$TMP_WORK_DIR"/.* > /dev/null 2>&1 || true

  # Move the files for the app back into the TMP_WORK_DIR
  mv "$APP_TMP_DIR/$app_subdir"/* "$TMP_WORK_DIR" > /dev/null 2>&1 || true
  mv "$APP_TMP_DIR/$app_subdir"/.* "$TMP_WORK_DIR" > /dev/null 2>&1 || true

  rm -rf "$APP_TMP_DIR"

  exit
done 10<"$TMP_WORK_DIR/.dokku-monorepo"

dokku_log_info2 "The application $APP is not defined in .dokku-monorepo!"
exit 1
