#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

APP="$1"; IMAGE_SOURCE_TYPE="$2"; TMP_WORK_DIR="$3"; REV="$4"

if [[ ! -f "$TMP_WORK_DIR/.dokku-monorepo" ]]; then
  true
else
  dokku_log_info2 "Monorepo detected"

  while IFS="=" read -u 10 -a line; do
    if [[ "${line[0]}" == "${APP##*-}" ]]; then
      app_root="$TMP_WORK_DIR/${line[1]}"
      dokku_log_info1 "Installing from ./${line[1]}"

      pushd "$root" > /dev/null
      if [[ -f Dockerfile ]] && [[ "$([[ -f .env ]] && grep -q BUILDPACK_URL .env; echo $?)" != "0" ]] && [[ ! -f ".buildpacks" ]]; then
        plugn trigger pre-receive-app "$APP" "dockerfile" "$root" "$REV"
        dokku receive "$APP" "dockerfile" "$app_root" | sed -u "s/^/"$'\e[1G'"/"
      else
        plugn trigger pre-receive-app "$app_name" "herokuish" "$root" "$REV"
        dokku receive "$APP" "herokuish" "$app_root" | sed -u "s/^/"$'\e[1G'"/"
      fi
      popd > /dev/null
    fi
  done 10<"$TMP_WORK_DIR/.dokku-monorepo"

  false
fi
